pipeline {
    agent any
    environment {
        DOCKERHUBCREDS = credentials('dockerhub')
        dockerhubUsername = "pain13"
    }
    parameters {
        choice(name: 'application',
            choices: 'webapp',
            description: 'Select the application to be deployed')
        choice(name: 'incrementMajorVersion',
            choices: 'yes\nno',
            description: 'yes=x+1.y and no=x.y+1')
    }
    stages {
        stage('Checkout - clone the repository') {
            steps {
                echo "====++++Cloning the repository++++===="
                checkout([$class: 'GitSCM', branches: [[name: 'master']],
                        extensions: [[$class: 'LocalBranch', localBranch: 'expected']],
                        userRemoteConfigs: [[url: 'https://github.com/jibran123/cicd',
                        credentialsId: 'jibran-github']]])
            }
            post {
                success {
                    echo "====++++Repository Cloned successfully++++===="
                }
                failure {
                    echo "====++++Could not cloned the repository. Please check the repo URL and credentials++++===="
                }
            }
        }
        stage("Check whether Docker is running") {
            steps {
                echo "====++++Executing Start Docker++++===="
                sh 'sh scripts/enableDocker.sh'
            }
            post {
                success {
                    echo "====++++Docker is now up and running. Moving on to check minikube++++===="
                }
                failure {
                    echo "====++++Please install docker manually and start the docker service by using `systectl start docker.service` command++++===="
                }
            }
        }
        stage("Build docker image and push it to dockerhub") {
            steps {
                echo "====++++Executing Build and Push Docker++++===="
                sh 'sh scripts/dockerImageBuilder.sh $dockerhubUsername $DOCKERHUBCREDS_PSW $application $incrementMajorVersion'
            }
            post {
                success {
                    echo "====++++Docker is now up and running. Moving on to check minikube++++===="
                }
                failure {
                    echo "====++++Please install docker manually and start the docker service by using `systectl start docker.service` command++++===="
                }
            }
        }
        stage("Check if Minikube is setup and running") {
            steps {
                echo "====++++Executing Check if Minikube is setup and running++++===="
                sh 'sh scripts/configureMinikube.sh'
            }
            post {
                success {
                    echo "====++++We are now ready to start deployment on k8 cluster++++===="
                }
                failure {
                    echo "====++++Please install minikube and start the minikube service by using minikube start command++++===="
                }
            }
        }
        stage("Check whether manisfest exists") {
            steps {
                echo "====++++executing Check whether manisfest exists++++===="
                sh "ls k8-manifests/$application/*.yaml"
            }
            post {
                success {
                    echo "====++++k8 manifests found successfully. Proceeding to deploy on k8 cluster++++===="
                }
                failure {
                    echo "====++++Could not find Manifest at specified location. Please check the repository and place the k8 manifests at correct location++++===="
                }
            }
        }
        stage("Update the new docker image version in manifest") {
            steps {
                echo "====++++executing Update the correct version in manifest++++===="
                sh "sh scripts/updateManifestToUseNewlyCreatedDockerImage.sh $dockerhubUsername $application"
            }
            post {
                success {
                    echo "Successfully updated manifest with newly created docker version"
                }
                failure {
                    echo "Failed to update the k8 manifests with new docker version. Please try again"
                }
            }
        }
        stage("Run yamllint test") {
            steps {
                echo "====++++Executing YAMLLINT on all k8 manifests++++===="
                sh 'sh scripts/yamllint.sh $application'
            }
            post {
                success {
                    echo "====++++No Errors found. Manifest looks great :). Proceeding with deployment++++===="
                }
                failure {
                    echo "====++++yamllint found errors. Please check logs for more details.++++===="
                }
            }
        }
        stage("Deploy to k8s cluster minikube") {
            steps {
                echo "====++++Executing Deploy to k8 cluster minikube++++===="
                sh 'kubectl apply -f k8-manifests/$application/'
            }
            post {
                success {
                    echo "====++++Succesfully Deployed to Minikube cluster++++===="
                }
                failure {
                    echo "====++++Failed to Deploy to minikube cluster++++===="
                }
            }
        }
        stage("Check minikube cluster") {
            steps {
                echo "====++++Waiting until pods are created and up and running++++===="
                sleep 60
                echo "====++++Checking the cluster to get the latest status of pods++++===="
                sh 'sh scripts/checkDeployments.sh ${application}'
            }
            post {
                success {
                    echo "====++++All pods are up and running. Deployment successful++++===="
                }
                failure {
                    echo "====++++All pods are not in healthy state. Please execute kubectl logs <podname> -n <namespace> to troubleshoot++++===="
                }
            }
        }
    }
}